/**
This file is generated by Smash
https://github.com/mbostock/smash/wiki

@module z-d3-lib-homevalues
@class d3
@namespace Z.External
@since 2013/11
@author jonathanf
**/
YUI.add('z-d3-lib-homevalues', function (Y) {

    var External = Y.namespace('External');

    External.d3 = function() {
        var d3 = {version: "3.3.9"}; // semver
